export const orderData = [
  {
    id: 1,
    userId: 1,
    products: [
      { productId: 1, name: "Laptop Pro 15", price: 1500 },
      { productId: 3, name: "Wireless Headphones", price: 200 },
    ],
    total: 1900,
    status: "pending",
    orderDate: "2026-02-10T10:30:00Z",
    tags: ["priority", "gift", "fragile"],
    shipping: {
      method: "Standard",
      trackingNumber: "TRK123456",
      address: { street: "123 Maple St", city: "Springfield", zip: "12345" },
      dimensions: { weight: 5, length: 50, width: 30, height: 15 },
    },
  },
  {
    id: 2,
    userId: 2,
    products: [{ productId: 2, name: "Smartphone X", price: 900 }],
    total: 900,
    status: "shipped",
    orderDate: "2026-02-08T15:45:00Z",
    tags: ["express", "electronics"],
    shipping: {
      method: "Express",
      trackingNumber: "TRK123457",
      address: { street: "456 Oak St", city: "Riverside", zip: "67890" },
      dimensions: { weight: 1, length: 18, width: 8, height: 2 },
    },
  },
  {
    id: 3,
    userId: 3,
    products: [
      { productId: 4, name: "Gaming Chair", price: 350 },
      { productId: 6, name: "Mechanical Keyboard", price: 120 },
    ],
    total: 470,
    status: "delivered",
    orderDate: "2026-02-07T12:20:00Z",
    tags: ["home-office", "gaming"],
    shipping: {
      method: "Standard",
      trackingNumber: "TRK123458",
      address: { street: "789 Pine St", city: "Greenville", zip: "54321" },
      dimensions: { weight: 12, length: 100, width: 60, height: 40 },
    },
  },
  {
    id: 4,
    userId: 4,
    products: [{ productId: 5, name: "4K Monitor", price: 450 }],
    total: 450,
    status: "cancelled",
    orderDate: "2026-02-12T09:10:00Z",
    tags: ["electronics", "office"],
    shipping: {
      method: "Standard",
      trackingNumber: null,
      address: { street: "321 Cedar St", city: "Hilltown", zip: "11223" },
      dimensions: { weight: 15, length: 120, width: 70, height: 50 },
    },
  },
  {
    id: 5,
    userId: 5,
    products: [
      { productId: 7, name: "Smartwatch Series 5", price: 300 },
      { productId: 3, name: "Wireless Headphones", price: 200 },
    ],
    total: 500,
    status: "returned",
    orderDate: "2026-02-09T18:50:00Z",
    tags: ["gift", "fitness"],
    shipping: {
      method: "Express",
      trackingNumber: "TRK123459",
      address: { street: "654 Birch St", city: "Lakeside", zip: "33445" },
      dimensions: { weight: 6, length: 45, width: 35, height: 15 },
    },
  },
  {
    id: 6,
    userId: 6,
    products: [
      { productId: 1, name: "Laptop Pro 15", price: 1500 },
      { productId: 2, name: "Smartphone X", price: 900 },
      { productId: 5, name: "4K Monitor", price: 450 },
    ],
    total: 2850,
    status: "delivered",
    orderDate: "2026-02-11T11:25:00Z",
    tags: ["bulk", "electronics"],
    shipping: {
      method: "Express",
      trackingNumber: "TRK123460",
      address: { street: "987 Elm St", city: "Mapleton", zip: "55667" },
      dimensions: { weight: 20, length: 150, width: 70, height: 50 },
    },
  },
  {
    id: 7,
    userId: 7,
    products: [{ productId: 6, name: "Mechanical Keyboard", price: 120 }],
    total: 120,
    status: "pending",
    orderDate: "2026-02-13T14:00:00Z",
    tags: ["gaming", "office"],
    shipping: {
      method: "Standard",
      trackingNumber: "TRK123461",
      address: { street: "159 Willow St", city: "Sunnyvale", zip: "77889" },
      dimensions: { weight: 5, length: 50, width: 20, height: 10 },
    },
  },
];
